/********************************************************
* Generated By:   zhumc

* Date Generated: 2007Äê10ÔÂ22ÈÕ
* ******************************************************/
using System;
using System.Data;
using System.Xml;
using System.Data.OracleClient;
using Epower.DevBase.BaseTools;
using Epower.ITSM.Base;
using Epower.DevBase.Organization.SqlDAL;
using Epower.DevBase.Organization.Base;
using EpowerGlobal;
using System.Xml;
using System.IO;
using EpowerCom;
using Epower.ITSM.Base;

namespace Epower.ITSM.SqlDAL
{
    /// <summary>
    /// Inf_OrderDealDP
    /// </summary>
    public class Inf_OrderDealDP
    {
        #region GetReadOrderData
        /// <summary>
        /// GetDataTable
        /// </summary>
        /// <param name="iNum"></param>
        /// <returns>DataTable</returns>
        public DataTable GetReadOrderData(int iNum)
        {
            string strSQL = string.Empty;
            OracleConnection cn = ConfigTool.GetConnection();
            strSQL = "SELECT  * FROM Inf_Information Where ROWNUM<=" + iNum.ToString() + " AND 1=1 And Deleted=0 Order by ReadCount desc";
            DataTable dt = OracleDbHelper.ExecuteDataTable(cn, CommandType.Text, strSQL);
            ConfigTool.CloseConnection(cn);
            return dt;
        }
        #endregion

        #region GetScoreOrderData
        /// <summary>
        /// GetScoreOrderData
        /// </summary>
        /// <param name="iNum"></param>
        /// <returns>DataTable</returns>
        public DataTable GetScoreOrderData(int iNum)
        {
            string strSQL = string.Empty;
            OracleConnection cn = ConfigTool.GetConnection();
            strSQL = "SELECT " + @" a.RegUserName,a.RegUserID,Round(Sum(nvl(b.Score, 0)),2) AllScore,Count(a.ID) iCount 
                         FROM Inf_Information a 
                        left outer join (select avg(Score) Score,KBID from Inf_Score Group by KBID) b On a.ID=b.KBID
                        Where ROWNUM<=" + iNum.ToString() + @" AND 1=1 And Deleted=0 
                        Group By a.RegUserName,a.RegUserID
                        Order  by  Round(Sum(nvl(b.Score, 0)),2) desc
                        ";
            DataTable dt = OracleDbHelper.ExecuteDataTable(cn, CommandType.Text, strSQL);
            ConfigTool.CloseConnection(cn);
            return dt;
        }
        #endregion
    }
}
