//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epower.ITSM.Web.AppForms {
    
    
    public partial class frm_BR_MEETINGSCHEDULED {
        
        /// <summary>
        /// Table2 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable Table2;
        
        /// <summary>
        /// CtrMeetingName 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Epower.ITSM.Web.Controls.CtrFlowFormText CtrMeetingName;
        
        /// <summary>
        /// CtrTitle 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Epower.ITSM.Web.Controls.CtrFlowFormText CtrTitle;
        
        /// <summary>
        /// CtrAddress 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Epower.ITSM.Web.Controls.CtrFlowFormText CtrAddress;
        
        /// <summary>
        /// ctrdropMeetingRoom 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Epower.ITSM.Web.Controls.ctrFlowCataDropListNew ctrdropMeetingRoom;
        
        /// <summary>
        /// CtrDepartmentName 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Epower.ITSM.Web.Controls.DeptPicker CtrDepartmentName;
        
        /// <summary>
        /// CtrHostNames 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Epower.ITSM.Web.Controls.UserPicker CtrHostNames;
        
        /// <summary>
        /// CtrPhone 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Epower.ITSM.Web.Controls.CtrFlowNumeric CtrPhone;
        
        /// <summary>
        /// Ctrdatetime 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Epower.ITSM.Web.Controls.CtrDateAndTime Ctrdatetime;
        
        /// <summary>
        /// ctrStartTime 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Epower.ITSM.Web.Controls.CtrDateAndTime ctrStartTime;
        
        /// <summary>
        /// ctrEndTime 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Epower.ITSM.Web.Controls.CtrDateAndTime ctrEndTime;
        
        /// <summary>
        /// cheService 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBoxList cheService;
        
        /// <summary>
        /// CtrRemarKs 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Epower.ITSM.Web.Controls.CtrFlowRemark CtrRemarKs;
        
        /// <summary>
        /// hidDeptID 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hidDeptID;
    }
}
